a = float(input("nhập phần thực của số phức z = "))
b = float(input("nhập phần ảo của số phức z = "))
z = complex(a,b)
print('số phức z =',z)
c = float(input("nhập phần thực của số phức w = "))
d = float(input("nhập phần ảo của số phức w = "))
w = complex(c,d)
print('số phức w =',w)
print('tổng 2 số phức =',z+w)
print('hiệu 2 số phức =',z-w)
print('tích 2 số phức =',z*w)
print('thương 2 số phức =',z/w)